{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flower.fullname" . }}
  labels:
    {{- include "flower.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "flower.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.metricsPortName }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
{{- end }}
